SERVER:
    PORT: 5555
    # NODE_ENV: 'production'
    NODE_ENV: 'development'
DB:
    TYPE: 'mysql'
    # HOST: 'localhost'
    HOST: '45.119.87.14'
    PORT: 3306
    USERNAME: 'root'
    PASSWORD: 'root'
    DATABASE: 'vv_account'
    SYNCHRONIZE: true
    MIGRATIONSRUN: false

JWT:
    SECRET_KEY: 'thisissecretkey'
    REFRESH_TOKEN_EXPIRATION_DAYS: 30
    RESET_PASSWORD_EXPIRATION_DAYS: 1
    ACCESS_TOKEN_EXPIRATION_DAYS: 1
    SALT: 10
